### ISSUE TITLE
[kong] make it possible to only install CRDs in a Helm release

### ISSUE THREAD

**Issue by hbagdi** [Kong/charts#135]
If Kong is being installed multiple times in a single k8s cluster, it should be possible to install CRDs as a release and then install all Kong releases without CRDs.

Associated CRDs with any of the releases results in all other releases to be broken when the release that includes CRDs is removed.

**Comment by rainest** [comment]
This is now effectively supported, but clunky: if you enable CRD installation and disable both the controller and Kong Pods, the chart does install the CRDs as a managed part of the release, and nothing else.

CRD management is inherently annoying because of the "delete CRD, delete all resources of that type footgun", which is kinda why Helm 3 takes a more hands-off approach (create CRDs if needed, but do not manage them along with the release) by default. That comes with its own problems related to CRD changes, but working within it is complicated so long as we support Helm 2 and Helm 3 both.

As-is, this is implemented, so closing this. We should revisit CRD management after removing Helm 2 support. #93 for that and related CRD discussion.
