### ISSUE TITLE
The helm chart does not support Kong ACME plugin

### ISSUE THREAD

**Issue by gurkanguran** [Kong/charts#153]
I have been trying to configure acme plugin for a while but I couldn't succeed. 
According to https://github.com/Kong/kong-plugin-acme, the plugin installation requires adding **lua_ssl_trusted_certificate** to kong.conf file 
or 
according to this document (https://docs.konghq.com/hub/kong-inc/acme/), it requires adding **nginx_proxy_lua_ssl_trusted_certificate** to kong.conf file.

I tried both passing under "env" as it is mentioned in the chart readme file. But it didnt work. Kong gateway pod is going into CrashBackLoop.

Can you please add support for ACME plugin to the helm chart or can someone guide me to install it properly ?

**Comment by rainest** [comment]
Cross-posting from https://discuss.konghq.com/t/guide-for-configuring-acne-plugin-on-k8s/6467:

Can you provide us `kubectl logs -c proxy KONG_POD_NAME` or `kubectl logs -c wait-for-db KONG_POD_NAME` output from the crashlooped Pod?

**Comment by rainest** [comment]
Good news! https://github.com/Kong/kong/pull/6342 is not yet released, but is scheduled for Kong 2.2. It adds two changes to `lua_ssl_trusted_certificate`:

- `lua_ssl_trusted_certificate` previously only allowed a single certificate, which required creating a bundle manually when using custom CAs. As of 2.2, it will allow you to provide a comma-separated list of CA files, and will concatenate them into a single bundlle for you when Kong starts.
- `lua_ssl_trusted_certificate` previously had no default. 2.2 will add a special `system` value that translates into the standard OS certificate bundle location.

If you're using LetsEncrypt, that means the ACME plugin should work without configuration changes on 2.2: as far as I know, all our standard images trust LetsEncrypt in their standard certificate bundle. If you're using your own ACME provider that issues certificates from a private CA, it's now easier to add it, since you'll be able to set something like `system, /path/to/private/ca.pem` to trust both the private CA and public CAs at once.

The chart won't require any additional features when using LetsEncrypt, but it does still need an easy means of adding private CA certs without building a custom image. https://github.com/Kong/charts/pull/208 should add that in the near future: it's currently undergoing review, but should get merged in after review changes and will allow easily mounting any file from a ConfigMap, including a private CA bundle.

Leaving this open for now as those changes are both still in progress; will return to close it once those are both released.
