### ISSUE TITLE
Add support for internal loadbalancer along with an external one

### ISSUE THREAD

**Issue by martinkubrak** [Kong/charts#170]
Currently KIC creates a single loadbalancer for all services. That usually would be an external (public IP) loadbalancer. However, it would be useful to have option to create two loadbalancers within the same KIC. Currently that would require to deploy a second KIC with a separate ingress class but that means that Kong CRs (plugins, consumers etc) would have to be duplicated since they are tied to a particular KIC class. Proposed solution is to extend Helm chart to add `SVC.internal.* ` parameter which would allow to deploy a second internal loadbalancer if needed. It's pretty much how it's solved in Nginx Ingress Controller [here](https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L300)

I'm happy to open a PR with this change.

**Comment by rainest** [comment]
@martinkubrak could you provide more detail on the rationale/problem you want to solve with this? It's probably something we'd accept if PRed, but understanding the use case would help us determine whether there are other things we'd want to address as well.

My main concern is that while you can attach multiple LoadBalancers to the same Kong proxy instance, there's no way to separate what configuration is available on that proxy instance, i.e. your internal routes would be exposed on the external LB as well as the internal LB, and vice-versa. That may be okay in some cases (e.g. you have separate internal and external load balancers because sending traffic to the latter counts as egress and is more costly than keeping traffic inside the LAN) but can be really bad in others (you want internal routes to only be accessible internally, and want to enforce this via network boundaries).

Another thing to note is that although resources can only have a single ingress class, there's no hard restriction on creating multiple controllers that process the same class. You can create two controller+proxy deployments, instruct both controllers to handle class `foo`, and each proxy will get the same set of configuration (effectively, at least--Kong resources will have different IDs, created at times, etc., but will have the same functional configuration). There's a soft limitation where Kubernetes resources only have the one status field, so the controllers will fight over that. It may well be possible to address that limitation, and may make more sense to approach it from that angle if we want to address the network isolation issue.

**Comment by martinkubrak** [comment]
@rainest thanks for reply. Problem I am trying to solve is a situation where I need to expose k8s services either externally or internally - in most cases it's to make certain services available on LAN only. In case of Nginx Ingress Controller I simply have two deployments with separate ingress classes and choose between the two in Ingress resources. As you pointed out the same can be done with KIC. The issue here is that I may have to create certain entities (consumers, credentials etc) twice for each controller which I would prefer to avoid.

Deploying two KICs (external and internal) with the same class would cause the same issue as having two LoadBalancers attached to the same KIC - the same Ingress would be available both internally and externally. I suppose a possible solution would be to deny access for specific hostnames in external KIC.

I suppose unless Kong resources can be attached to more than one KICs class at the same time the only way to achieve network isolation is to deploy two KICs and duplicate Kong resources as needed.

**Comment by rainest** [comment]
Yeah--you kinda can have multiple controllers consume the same resource, but IMO it gets hacky real quick. @hishamhm on the proxy core end, has there been any thought around splitting up proxy listens for this sort of network isolation?

**Comment by amgmdz** [comment]
I have a similar problem, I am using Kong as Api Gateway. I would like to expose public frontend routes and different pod (Apis) routes that are internal but even when creating the routes they always end up being public. What is the correct way to separate which route should be public and which should be private?

I did a test to generate a second internal loadbalancer but I would have to find a way to create a perzonalized class for kong (for example: kong-internal) that points to the new loadbalancer, so that I can call it when creating the internal route with: kubernetes.io/ingress.class: kong-internal

**Comment by mflendrich** [comment]
This appears to be a convenience/"nice to have" issue that results in duplicated configuration but not significant functional change.

**Comment by mflendrich** [comment]
Closing as "won't fix" - the current recommended approach is deploying two separate ingress controllers. Please comment if you're interested in this feature and the recommendation doesn't work well for you.
