### ISSUE TITLE
smtp_auth_type and smtp_mock missing from values.yaml

### ISSUE THREAD

**Issue by felderi** [Kong/charts#180]
When attempting to setup smtp, came across the fact smtp_auth_type and smtp_mock was missing from the values.yaml.  This setting is required to enable smtp.

**Comment by rainest** [comment]
`auth_type` was added 3 months prior to the opening of this issue: https://github.com/Kong/charts/pull/127

mock is de facto handled by `smtp.enabled`. If that's off, mock is on. If it's on, mock is off. That's covered in [the documentation](https://github.com/Kong/charts/tree/kong-1.10.0/charts/kong#emailsmtp) and can be quite readily found by inspecting [the templates](https://github.com/Kong/charts/blob/kong-1.10.0/charts/kong/templates/_helpers.tpl#L528-L547).

I will admit that the structure of those settings in values.yaml is a bit confusing. It's an unfortunate shim against the SMTP configuration being pretty user-unfriendly at the kong.conf level. The SMTP subsystem doesn't degrade gracefully and will block Kong from starting when some settings are omitted, so the dedicated SMTP section enumerates those critical settings to try and force you to populate all of them (failing that, it will forcibly populate them with junk values, so that Kong will at least start even if it cannot actually send mail.

While I wholeheartedly agree that those settings could be more user-friendly/that would we could find some better way of guiding users through setting them up, that should ideally be done by reworking the settings themselves, not by trying to cover over their user-unfriendliness with tooling over top of them.
