### ISSUE TITLE
Environment variable KONG_NGINX_HTTP_INCLUDE cannot be safely set/remove legacy config-custom-server-blocks.yaml template

### ISSUE THREAD

**Issue by ovlad** [Kong/charts#206]
For redirecting all HTTP requests to HTTPS, I was trying to include a custom Nginx configuration file that contains an Nginx `server` directive, following [this](https://docs.konghq.com/2.1.x/configuration/#including-files-via-injected-nginx-directives) official docs, setting the environment variable `KONG_NGINX_HTTP_INCLUDE` like this:
```yaml
env:
    nginx_http_include: /usr/local/kong/custom-nginx-kong.conf
```
After installing the chart, the Kong's main pod does not start because of the probes failure, and that's because the chart [also sets](https://github.com/Kong/charts/blob/main/charts/kong/templates/_helpers.tpl#L554) the `KONG_NGINX_HTTP_INCLUDE` variable, and my value overrides the chart `/kong/servers.conf` value.
The workaround would be to include in my configuration file all the the content from `/kong/servers.conf`, but it doesn't seem the right way to handle this.

**Comment by hbagdi** [comment]
Can you change the probe in that case? If you are not securing the Admin API, you could use port 8001 for health/ready probes.

**Comment by rainest** [comment]
The existing servers.conf is scheduled for removal, as the functionality it provides now exists natively via the Kong status listen. We should probably still provide a chart-specific means of injecting configuration into the root `http` block for custom server blocks, however, as that's still better handled via a ConfigMap in a Kubernetes context (you have to build a custom image with the extra configuration file otherwise).

That effectively breaks compatibility with older versions of Kong, however, so it's deferred until the 2.0 major release. While that's planned, it's after the upcoming major Kong Ingress Controller release (tentatively, that should put Kong chart 2.0 sometime later this year).

Using a forked chart that modifies https://github.com/Kong/charts/blob/main/charts/kong/templates/config-custom-server-blocks.yaml (which is what we mount at `/kong/servers.conf`) is the recommended option for now, it's just inconvenient. However, that file shouldn't change going forward (as it's effectively deprecated), so you shouldn't need to integrate changes to it--you'd rebase your fork as future 1.x chart releases come out, but should never encounter conflicts.

Keeping this open with a modified title indicating the future change, as we'd not created one previously.

**Comment by mflendrich** [comment]
Done per #255
