### ISSUE TITLE
Clear text http/2

### ISSUE THREAD

**Issue by cosmin-mogos** [Kong/charts#216]
What is the simplest way to configure the 3 proxy ports below using the kong chart?
* http clear text
* http/2 clear text
* http/2 tls

**Comment by rainest** [comment]
You can set parameters for the proxy [HTTP](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L180) and [HTTPS](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L193-L194) listens, which correspond to NGINX listen parameters. We append `ssl` to the HTTPS listen parameter list automatically when rendering the template.

The underlying [NGINX listens do not have support for cleartext http/2, however](https://trac.nginx.org/nginx/ticket/808); there's not really any good way around that. You can define a [TCP stream listen](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L196-L210) to handle it separately, though that will have other implications, since plain TCP routes are handled differently and won't have the full functionality offered by HTTP-aware plugins.
