### ISSUE TITLE
Migrations job created in kubernetes using kong/kong chart

### ISSUE THREAD

**Issue by wheestermans31** [Kong/charts#235]

**Comment by wheestermans31** [comment]
And this job includes the "kong migrations bootstrap" command.

**Comment by wheestermans31** [comment]
What I execute is a helm install to install a 2.1 release next to the already running 1.5 release

**Comment by wheestermans31** [comment]
Previously we used the stable/kong chart, there it seems this Job manifest one is not created. When using the kong/kong, the Job manifest is created.

**Comment by rainest** [comment]
This is a bug in our template logic introduced along with the per-migration toggles. There's a `migrations.init` toggle in addition to the other per-migration toggles that we intentionally hide, as it should generally always be enabled (while the `preUpgrade` and `postUpgrade` toggles are required for some types of upgrades, but there shouldn't be any workflows that don't bootstrap the database, and running the job is at worst a no-op if the database is already bootstrapped).

Do you have a workflow where disabling it is indeed desirable, or were you just curious why `runMigrations` wasn't disabling it? If there are use cases where disabling it makes sense, it may make sense for us to document it.

#247 will address this for either `runMigrations` or `migrations.init` settings.

**Comment by mflendrich** [comment]
Any reason against dropping the `runMigrations` flag whatsoever?

If there's concern that somebody might upgrade and fail to notice that `runMigrations` is no longer supported by us, we might add a check that fails template rendering if that flag is not unset.

Otherwise, with two parallel feature flag sets covering the same thing, we fall prey to logical errors.
