### ISSUE TITLE
Invalid pod annotation for user-provided webhook certs

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#252]
Per https://github.com/Kong/charts/issues/126

> you can specify your own certificate, but the chart will always add the checksum annotation regardless

Current behavior: when the user provides a custom admission controller webhook certificate, an annotation on KIC pods includes a checksum of another (auto-generated) certificate, which differs from run to run, causing unnecessary pod restarts
Desired behavior: when the user provides a custom webhook certificate, subsequent helm updates shoud not modify the cert checksum annotation, and therefore not lead to a rolling restart of pods

cc @agaffney who originally reported this issue

**Comment by rainest** [comment]
Alright, this is more difficult than expected. I thought that you'd be able to just add your own Secrets with the names we use for the generated certificate and lookup would use that, but the chart attempts to [create new Secrets](https://github.com/Kong/charts/blob/kong-1.14.3/charts/kong/templates/admission-webhook.yaml#L38-L66) with that content, and they'll collide: 

> rendered manifests contain a resource that already exists. Unable to continue with install: Secret "release-kong-validation-webhook-ca-keypair" in namespace "whatever" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "release"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "whatever"

We can't condition the those blocks on the lookup succeeding because if the certs _were_ auto-generated, an upgrade that doesn't include those blocks will delete the Secrets.

Furthermore, functionality for setting your own certificate doesn't actually exist yet--the quoted bit from my old comment in this issue should have been a hypothetical about how we'd handle the checksum if you could. There are a couple things to keep in mind if we want to add that:
- The file and value certificate flags [are mutually exclusive](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/cli/ingress-controller/main.go#L501-L507). We'd need to auto-detect either type of user configuration in controller env if we don't provide a dedicated setting to disable certificate generation.
- `caBundle` configuration for the hook is optional but absolute: if you do provide it, the API server won't trust webhook client certificates issued by the cluster CA.

If we require that all users sign certificates they provide with the cluster CA, life is simple: we just add an `ingressController.admissionWebhook.generateCertificate` setting, disable all the certificate generation stuff if it's off, and ask users to set `ingressController.env.admission-webhook-cert`/`ingressController.env.admission-webhook-key`.

If we do want to allow using a custom `caBundle`, we have to be prescriptive about the format and either ask users to dump the whole PEM into values.yaml (works, but ugly), ask for a Secret or ConfigMap with a particular key (restrictive, but we [do it elsewhere](https://github.com/Kong/charts/blob/kong-1.14.3/charts/kong/values.yaml#L574-L577), or ask for both a Secret and key. Alternatively, we ask users to patch after install, either manually (relying on Helm 3 diff logic to preserve the change) or via [post-rendering](https://helm.sh/docs/topics/advanced/#post-rendering).

**Comment by rainest** [comment]
Didn't get a chance to discuss this in planning today, but as user-provided certificates are in fact new functionality, moving this back to the groomed backlog. I don't want to tackle it until #256 is in place, and that will be a while--it's effectively done, but can't actually be merged in until other work to migrate to a Helm 3 only chart is complete.

**Comment by ludovic-pourrat** [comment]
See https://github.com/Kong/charts/pull/385 that provide a solution proposal for this feature request.
