### ISSUE TITLE
[kong] Bump Kong to 2.3

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#291]

**Comment by guanlan** [comment]
https://konghq.atlassian.net/wiki/spaces/FTT/pages/2031124482/2021-01-22+CP+-+DP+Version+and+plugin+list+compatibility

Some of the discussions happens for the version compatibility.

**Comment by mflendrich** [comment]
Blocked: pending verification that Kong `2.3` has the loosened version check that allows 2.2 DPs with a 2.3 CP.

**Comment by rainest** [comment]
Somewhat unsure what we want to verify here; do we just want to double-check that the change in https://github.com/Kong/kong/pull/6612 works as designed for both the version difference and plugin list difference?

I don't think that'd influence our decision to change the default versions, since the expectation there is that we just keep those at the latest version for new installs, but that existing installs preserve their versions in values.yaml anyway to avoid unintended Kong version upgrades from a chart upgrade. That's [already part of our guidance](https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md#upgrade-considerations-for-all-versions), though we can perhaps clarify that a bit to indicate that you should always include image versions in your release's values.yaml.

**Comment by rainest** [comment]
I should do better at remembering things I discussed this morning. There's a 2.3 bug that we probably want addressed before this bump. https://github.com/Kong/kong/issues/6827 affects us since the wait-for-db container's behavior counts as a restart, effectively breaking any install that uses stream listens.

 a0a342f  can work around that temporarily in CI and is available to users also, but isn't the most intuitive fix.
