### ISSUE TITLE
ServiceMonitor does not select for kong CP 

### ISSUE THREAD

**Issue by ttony** [Kong/charts#311]
Hi,

serviceMonitor is generated for Kong CP however, there is missing enabled-metrics in kong admin service.

serviceMonitor.yaml:
```javascript 
  selector:
    matchLabels:
      enable-metrics: "true"
      {{- include "kong.metaLabels" . | nindent 6 }}
```

service-kong-admin.yaml:
```javascript
  labels:
    enable-metrics: "true" -----> missing part
    {{- include "kong.metaLabels" . | nindent 4 }}
```

Helm Chart: 1.15.0

**Comment by ttony** [comment]
it is actually works by adding 

```javascript
   admin:
     labels:
       metrics-enabled: "true"
```

Please update the values.yaml documentation so that it is much easier for end user to find.

**Comment by shaneutt** [comment]
Yes I've looked through the templates and documentation, and while `enable-metrics` is the label we select on for metrics it's not well documented how to add that to components like the admin API, I'll put in a PR to improve this thanks for the report @ttony.

**Comment by rainest** [comment]
We don't cover this in values.yaml because the `labels` value on Services is generic, for adding any label, and documentation there is intentionally terse, since it's not hypertext and scrolling through is the only way to navigate it.

We do cover this for proxy-less instances at https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration

**Comment by shaneutt** [comment]
Just in case it's helpful to add a little bit more context to the `values.yaml`, I did add a note in https://github.com/Kong/charts/pull/345 that's intended to help.
