### ISSUE TITLE
Invalid template syntax 

### ISSUE THREAD

**Issue by ttony** [Kong/charts#313]
When you are using helm sdk and error:

[ERROR] Have some error in upgrading helm chart : parse error at (igw-cp/charts/kongHybrid/charts/kong/templates/service-kong-proxy.yaml:13): "-" 

service-kong-proxy.yaml:

```javascript
{{ if (not (hasKey .Values.proxy.ingress "hosts"))  -}}
```
so, to fix it temporary. i remove the "-" at the end as:

```javascript
{{ if (not (hasKey .Values.proxy.ingress "hosts"))  }}
```

**Comment by rainest** [comment]
Can you provide more details or an example program we can replicate this? To confirm, are you rendering the chart using [the Go SDK](https://helm.sh/docs/topics/advanced/#go-sdk) instead of the CLI helm tool? Does this issue happen with the current next branch of the chart as well?

This particular section of the template is for handling legacy proxy ingress configuration. We do test both variants currently, via 
https://github.com/Kong/charts/blob/kong-1.15.0/charts/kong/ci/test4-values.yaml#L53-L57 (for legacy) and https://github.com/Kong/charts/blob/main/charts/kong/ci/test1-values.yaml#L39-L43 (non-legacy).

When I run `helm template`, it doesn't complain with either, but I believe it performs some additional post-processing on the output, since the resulting Ingress and Service definitions get separated. It's possible that doesn't happen when using the SDK, though it's not clear why that newline chomp would cause an issue.

The legacy handling will go away entirely in the next release of the chart (which is currently staged in next). I'd want to target any fix for that instead if the issue is still present.

**Comment by ttony** [comment]
Hi Rainest, 

we can close this for time being as i can see the code has been lot of changes. let's close this.
