### ISSUE TITLE
Configuration option to allow servicePort name 

### ISSUE THREAD

**Issue by piyushpgupta** [Kong/charts#333]
As of now kong service port name is autogenerated.
we have validation webhook which restrict service port name to be in particular format .It will be great if option is allowed .I opened the PR for same : https://github.com/Kong/charts/pull/332 . I checked the fix with kong operator in local minikube .

**Comment by mflendrich** [comment]
Hi @piyushpgupta,

As explained in https://github.com/Kong/charts/pull/332#issuecomment-814480892, in order to keep the chart maintainable, we cannot allow endless flexibility in the chart code, because that would mean adding too much complexity over time. Have you tried writing a post-renderer for your case, as described the linked comment?
