### ISSUE TITLE
Enhancement: add support for NetworkPolicies

### ISSUE THREAD

**Issue by slawekww** [Kong/charts#335]
Following security pattern for kuberntes, 
I recommend to implement NetworkPolicies to be supported by helm chart:
https://kubernetes.io/docs/concepts/services-networking/network-policies/

Once enabled, create NetworkPolicies which open only required ports + allow to define custom policies, for example use LoadBalancer.

Many examples: https://github.com/ahmetb/kubernetes-network-policy-recipes

**Comment by mflendrich** [comment]
Hi @slawekww ,

Since network policies are highly environment-specific (and their exact form should depend on how you shape the traffic around KIC and Kong proxy that goes beyond `values` passed to the chart), I think that we cannot solve the general case with the helm chart.

Also I believe that a blanket setting along the lines of "flip this toggle to enable network policies for the ingress controller" can be tricky:
- it won't have a chance to be a complete network partitioning solution by default,
- it will come with potentially disastrous breaking changes if we decide to add/remove policies over time,
- I don't immediately see how "allow to define custom policies" would be better than the user just creating these network policies directly.

Therefore closing this issue as "won't fix" for now, but thoughts about how to overcome the problems above are welcome.
