### ISSUE TITLE
RBAC is disabled! Configuration will not be applied until RBAC is enabled.

### ISSUE THREAD

**Issue by uncodead** [Kong/charts#357]
I installed Kong enterprise on my CRC (openshift) and when i entering on Manager, I get the title message, even configuring kong for RBAC=on.

ENV VARS:
KONG_ADMIN_ACCESS_LOG | /dev/stdout
KONG_ADMIN_API_URI | http://
KONG_ADMIN_ERROR_LOG | /dev/stderr
KONG_ADMIN_GUI_ACCESS_LOG | /dev/stdout
KONG_ADMIN_GUI_AUTH | basic-auth
KONG_ADMIN_GUI_ERROR_LOG | /dev/stderr
KONG_ADMIN_GUI_LISTEN | 0.0.0.0:8445 http2 ssl
KONG_ADMIN_GUI_SESSION_CONF | secret: kong-session-config/admin_gui_session_conf
KONG_ADMIN_GUI_URL | https://manager-kong-kong.apps-crc.testing
KONG_ADMIN_LISTEN | 0.0.0.0:8444 http2 ssl
KONG_CLUSTER_LISTEN | off
KONG_CLUSTER_TELEMETRY_LISTEN | off
KONG_DATABASE | postgres
KONG_ENFORCE_RBAC | on
KONG_KIC | on
KONG_LUA_PACKAGE_PATH | /opt/?.lua;/opt/?/init.lua;;
KONG_NGINX_WORKER_PROCESSES | 2
KONG_PASSWORD | secret: kong-enterprise-superuser-password/password
KONG_PG_HOST | my-kong-postgresql
KONG_PG_PASSWORD | secret: my-kong-postgresql/postgresql-password
KONG_PG_PORT | 5432
KONG_PLUGINS | bundled
KONG_PORTAL | on
KONG_PORTAL_API_ACCESS_LOG | /dev/stdout
KONG_PORTAL_API_ERROR_LOG | /dev/stderr
KONG_PORTAL_API_LISTEN | 0.0.0.0:8447 http2 ssl
KONG_PORTAL_API_URL | https://portalapi-kong-kong.apps-crc.testing
KONG_PORTAL_GUI_HOST | portal-kong-kong.apps-crc.testing
KONG_PORTAL_GUI_LISTEN | 0.0.0.0:8446 http2 ssl
KONG_PORTAL_GUI_PROTOCOL | https
KONG_PORT_MAPS | 80:8000, 443:8443
KONG_PREFIX | /kong_prefix/
KONG_PROXY_ACCESS_LOG | /dev/stdout
KONG_PROXY_ERROR_LOG | /dev/stderr
KONG_PROXY_LISTEN | 0.0.0.0:8000, 0.0.0.0:8443 http2 ssl
KONG_SMTP_MOCK | on
KONG_STATUS_LISTEN | 0.0.0.0:8100
KONG_STREAM_LISTEN | off
KONG_NGINX_DAEMON | off

**Comment by RomeroGaliza** [comment]
Maybe this has something to do with the beta resources still being used instead of v1:

`rbac.authorization.k8s.io/v1beta1`

**Comment by uncodead** [comment]
> Maybe this has something to do with the beta resources still being used instead of v1:
> 
> `rbac.authorization.k8s.io/v1beta1`

Where did you see that?

**Comment by rainest** [comment]
Does the admin API indicate that RBAC is enabled? `GET /` will return a JSON document that includes an `enforce_rbac` key that indicates the actual setting at runtime (alternately, you may get rejected due to lack of a token, which indicates RBAC is indeed on).

If that environment variable is set as shown, there's not anything more the chart can do. From that point onward it's up to Kong to correctly read it, though I don't know of any reason it wouldn't.

The GUI doesn't read the RBAC setting directly: Kong generates a kconfig.js file in its temporary directory (`/kong_prefix`) when starting up, and the GUI reads that. It's possible for that to somehow get stuck with an incorrect value (e.g. if permissions don't allow Kong to overwrite it), but that shouldn't happen with the chart, since that location is is a fresh emptyDir mount created each time the Pod starts.

The K8S RBAC resource situation is unrelated and doesn't result in this message.

**Comment by ashutosh-elivaas** [comment]
Even After enabling` KONG_ENFORCE_RBAC=on` I am still getting the message of ```RBAC is disabled! Configuration will not be applied until RBAC is enabled.```.
