### ISSUE TITLE
Readiness probe fails if status.http.enabled = false

### ISSUE THREAD

**Issue by michbeck100** [Kong/charts#365]
I moved from http to tls for the status listener:

```yaml
status:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
```
But after deploying the changes, the readiness probe fails. It seems that the readiness readiness probe of the deployment relies on `status.http.enabled = true`.

**Comment by rainest** [comment]
It's configuration-dependent. Since the readiness and liveness probes [are fully exposed in values.yaml](https://github.com/Kong/charts/blob/kong-2.1.0/charts/kong/values.yaml#L462-L485), we can't automatically infer the correct protocol based on what's enabled in the listen (similar to how we handle controller<>admin API communication) in a template.

The status listen originally lacked HTTPS support, so we likely won't change that default for a while to preserve compatibility with older Kong versions. Not sure if we'd need to worry about the lack of a signed certificate by default after (we probably can--K8S docs indicate that the probe [ignores certificate validity by default](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes).

If you change the scheme in the values.yaml probe configuration also, does the release come online successfully?

**Comment by michbeck100** [comment]
> If you change the scheme in the values.yaml probe configuration also, does the release come online successfully?

@rainest which part of the values.yaml do you mean? 

> Not sure if we'd need to worry about the lack of a signed certificate

I wouldn’t worry about this, because every user can have his own custom certificate. 

If you can’t infer which protocol to use, you should maybe remove the option to disable the http listener.

**Comment by rainest** [comment]
> which part of the values.yaml do you mean?

https://github.com/Kong/charts/blob/kong-2.1.0/charts/kong/values.yaml#L462-L485

**Comment by michbeck100** [comment]
Changing the scheme and the port works. Thank you! A little feature request would still remain. What i had to do was this:

```yaml
readinessProbe:
  httpGet:
    port: status-tls
    scheme: HTTPS

livenessProbe:
  httpGet:
    port: status-tls
    scheme: HTTPS
```
It would be great if the helm template would automatically set `port` and `scheme` based on `status.tls.enabled`

**Comment by rainest** [comment]
Yeah, but we can't set them automatically while also pulling the configuration from values.yaml.

If you're interested in submitting a PR that reworks the check templates to have _no_ default in values.yaml and auto-populate based on the status listen configuration, with the ability to override them if they are indeed set in values.yaml, we'd be willing to accept it, but it's not a priority feature for us to develop independently.

**Comment by fellipecmwbc** [comment]
Hi guys, I am having the same issue, I have changed the port name and scheme, but I am getting this error:
`Warning  Unhealthy  3s                kubelet            Readiness probe failed: Get "https://172.18.3.77:20401/status": http: server gave HTTP response to HTTPS client`
Any ideas if I am missing anything here please? I see the port is registered as expected: `proxy-tls:8443,status-tls:8543`
I am using the chart version 2.7.0.
