### ISSUE TITLE
Kong binary not found with new docker image

### ISSUE THREAD

**Issue by ghost** [Kong/charts#367]
Hi !

I want update the docker image for kong with the new repository. 

I add the image `kong/kubernetes-ingress-controller:1.3.0`.

When I apply my helm chart I have the following error 

`/bin/sh: kong: not found`

Can you update the documentation and helm chart with the new repository please ?

**Comment by rainest** [comment]
Can you confirm what your [Kong image](https://github.com/Kong/charts/blob/kong-2.1.0/charts/kong/values.yaml#L69-L71) is? Do you use a custom image?

The controller image/container shouldn't throw that error, since we don't execute `kong` in it. That error should come one of the migrations containers, where we do. However, the standard (official) image shouldn't have any such issue--it does include a `kong` executable that's available from its `PATH`.

**Comment by ccfishk** [comment]
You can try k8s command : kubectl -n kong create deployment ingress-kong  to kong/kubernetes-ingress-controller:1.3.0 isolate docker issue or local command tool issue.
