### ISSUE TITLE
question: considerations when upgrading from 1.x chart

### ISSUE THREAD

**Issue by jam01** [Kong/charts#368]
Is the values.yaml backwards compatible? Is that the only thing to consider?

**Comment by rainest** [comment]
Do you indeed mean backwards (i.e. you can take a 2.x values.yaml to 1.x and still have it work) or forwards (you can take your existing 1.x values.yaml and upgrade to 2.x without changes)?

The answer is essentially yes to both, though it depends on exactly what you have in it. _Most_ values.yaml settings are unchanged between 1.x and 2.x. There are a select few settings that, on 1.x, supported an older configuration format, covered in the [deprecated features removed in 2.x](https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md#support-for-deprecated-1x-features-removed) section of the upgrade guide.

1.x gradually added support for the new versions over time, and if you're _reverting_ from 2.x to 1.x, you can use the format 2.x uses so long as you're downgrading to a version after the new format was added and the original format was removed (e.g. you can use the `migrations` setting block from 2.x as far back as 1.5). As such, the config format in 2.0 is largely backwards-compatible with 1.x, though the degree varies. We are not guaranteeing this going forward, however, and will add new functionality and/or deprecations that are not 1.x backwards-compatible in future 2.x versions.

Forwards compatibility depends on your replacing any old-format/deprecated config before upgrading from 1.x to 2.x. If any deprecated configuration is present, 1.14 will print a warning when you upgrade or install a release. If you see no warnings, your config is ready for 2.x.

The one quasi-exception to the above is the [proxy ingress host configuration](https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md#removal-of-multi-host-proxy-ingress). Although the above still applies, the old format for that was deprecated relatively late (in 1.14, the second-to-last 1.x release before 2.x), so that configuration is not backwards-compatible very far. However, we expected that actual use of the proxy Ingress was probably uncommon (probably only in environments where Kong was behind another proxy+ingress controller). You can make that section of the config backwards-compatible further by simply omitting it if you do not use it.

Will go ahead and close this, but if you have any follow-up questions, please respond back and I'll reopen it.

**Comment by jam01** [comment]
That's exactly what I was asking, thank you very much :pray:
