### ISSUE TITLE
Kong migration job args extension

### ISSUE THREAD

**Issue by ttony** [Kong/charts#386]
Hi Kong Team,

I would like to make ENV var KONG_PASSWORD only been set or used in kong migration only so that the generated yaml is clean, since KONG_PASSWORD is only applicable during the boostrap migration job only.

Also, I would like to try to highlight about the one of the best practice, such as CKV_K8S_35 (Prefer using secrets as files over secrets as environment variables).  

The generated bootstrap job yaml is something like this:

```yaml
  containers:
  - args: [ "/bin/sh", "-c", "export KONG_PASSWORD=`cat /etc/secrets/kong/password` && kong migrations bootstrap -vv" ]
```

we can use it as default values for it.

```yaml
migrations:
     additionalArgs: ""
     additionalPreUpgradeArgs: ""
     additionalPostUpgradeArgs: "" 
```

migration template is something like this:

```yaml
  containers:
  - args: [ "/bin/sh", "-c", "{{ .Values.migrations.additionalArgs }} kong migrations bootstrap" ]
```

pre-upgrade migration template:
```yaml
  containers:
  - args: [ "/bin/sh", "-c", "{{ .Values.migrations.additionalPreUpgradeArgs }} kong migrations up" ]
```

post-upgrade migration template:
```yaml
  containers:
  - args: [ "/bin/sh", "-c", "{{ .Values.migrations.additionalPostUpgradeArgs }} kong migrations finish" ]
```

Let me know your feedback

**Comment by rainest** [comment]
Do you have further information on the CKV_K8S_35 recommendation? I'm not able to find much anything on it other than Bridgecrew's reference pages and blog, and the rationale there (that environment variables may show up in application logs) seems quite limited, and not applicable here (we do not log that value and intentionally mark sensitive values for redaction in our startup logs). Were this a widely accepted recommendation, I'd expect to see it in official Kubernetes documentation, e.g. https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ and https://kubernetes.io/docs/concepts/configuration/secret/#security-properties

Injecting user-provided free text into the migrations commands in the chart is a rather roundabout way to address this in either case. I'd recommend instead:
- Continue using the environment variable, but remove it from values.yaml and running `helm upgrade` after bootstrapping to clear it from the Deployment and subsequent Jobs.
- If you do indeed want to load it from a file mount instead, submit a feature request for Kong Enterprise upstream to request alternate RBAC bootstrap options.

**Comment by ludovic-pourrat** [comment]
We have the same concern about securing the Kong related secrets, which are secured in Vault in our case, and we plan to leverage the `_FILE` lookup for environment variables done by the Docker entry point, see below.

https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh

This allows setting up the KONG_PASSWORD  via the KONG_PASSWORD_FILE if accepted, see https://github.com/Kong/docker-kong/issues/488

But finally the migrations command should be set to `args: [ "kong", "migrations" ,"bootstrap" ]`  to take benefit from the standard entry point instead of the /bin/sh. See https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

We have successfully validated this approach.

Ideas / thoughts ?

**Comment by rainest** [comment]
Thought there was some reason we used the `sh` arg there, but apparently not, so https://github.com/Kong/charts/pull/429

@ttony though docker-kong#488 isn't implemented yet, it's be a better solution than #422 IMO, since it has dedicated functionality to load files rather than asking users to modify the arg directly and roll their own file loader. Do you agree/think it'd make sense to close #422 and wait for that instead?

**Comment by ludovic-pourrat** [comment]
The migrations commands are fixed in the 2.3.0 release.

**Comment by rainest** [comment]
As there hasn't been any objection to the proposed solution in https://github.com/Kong/charts/issues/386#issuecomment-892171572 and the [docker-kong feature](https://github.com/Kong/docker-kong/issues/488) is now available as of https://github.com/Kong/docker-kong/pull/490, closing this with the recommendation that anyone seeking this functionality handle it via the docker-kong functionality.

**Comment by rainest** [comment]
Closing per https://github.com/Kong/charts/issues/386#issuecomment-911883119
