### ISSUE TITLE
ServiceAccount can't be created if not using ingressController

### ISSUE THREAD

**Issue by ichasco-heytrade** [Kong/charts#418]
Hi,

I have a problem because I use the serviceAccount but I don't use IngressController. And with the last changes, It's impossible to use it. Also I need to mount the token because I use vault-secret-webhook and for this is necessary. Can be this optional and enable it by any environment?

Is there any workaround to fix it? 

Thanks

**Comment by rainest** [comment]
Which change did you see cause this, or what chart versions did you upgrade to/from that you saw this break?

There are [conditions that gate the creation of the ServiceAccount](https://github.com/Kong/charts/blob/kong-2.2.0/charts/kong/templates/controller-service-account.yaml#L1), but they've always been in place and haven't changed in quite some time.

We'd be open to accepting a PR that makes it independent of the controller and PSP. The tricky part is making it compatible with the existing configuration under the ingressController section--we wouldn't want to interfere with that and break existing configuration on upgrades.

If you decide to add a PR, I'd suggest creating a new `serviceAccount` section under the [deployment section of values.yaml](https://github.com/Kong/charts/blob/kong-2.2.0/charts/kong/values.yaml#L16) with the same contents [as the existing section](https://github.com/Kong/charts/blob/kong-2.2.0/charts/kong/values.yaml#L422-L429), but with `create` set to `false`.

You can then create a helper function in _helpers.tpl that renders either the original ServiceAccount (from the configuration under `ingressController`), the new one if enabled (i.e. if it has either `create: true` or its `name` field set), or an empty string if neither are enabled, and replace the existing `serviceAccountName` blocks (e.g. https://github.com/Kong/charts/blob/kong-2.2.0/charts/kong/templates/migrations.yaml#L42-L44 and https://github.com/Kong/charts/blob/kong-2.2.0/charts/kong/templates/deployment.yaml#L62-L64) with that helper.

That pattern should allow you to configure a ServiceAccount independently while maintaining compatibility with existing configuration.

**Comment by ichasco-heytrade** [comment]
Hi, the problem I have is that I need the `automountServiceAccountToken` enabled without enabling `ingressController`
Could be something like:
```
...
ingressController:
  enabled: false
...
  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name:
    # The annotations for service account
    annotations: {}
    automountServiceAccountToken: true
...
```
Thanks!

**Comment by ludovic-pourrat** [comment]
Hi,
I am looking for the same feature to allow the chart to create a service account, and I do agree @rainest comment, but is the code below a bit confusing and related to @ichasco-heytrade comment ?

> {{- define "kong.serviceAccountName" -}}
> {{- if .Values.ingressController.serviceAccount.create -}}
>     {{ default (include "kong.fullname" .) .Values.ingressController.serviceAccount.name }}
> {{- else -}}
>     {{ default "default" .Values.ingressController.serviceAccount.name }}
> {{- end -}}
> {{- end -}}

We might rename the helper `kong.serviceAccountName` to `kong.ingressController.serviceAccountName` to allow the addition of a feature to create a serviceAccount for Kong ?

Thanks.

**Comment by rainest** [comment]
@ludovic-pourrat not sure what's confusing in the snippet. It's just determining the account name based on the combination of the `create` and `name` settings, either returning the name you set or a default name. The path that uses `default` as the name if you set `create` off but don't provide a name is a bit odd, but whatever.

We'd keep the single `kong.serviceAccountName` function, since the proposed change here wouldn't create an additional, separate account: you can only have the one ServiceAccount bound to the Pod (which contains both Kong and the controller), so you wouldn't get two accounts, one for the controller and one for Kong.

The change I'm suggesting is that you create a new section of values.yaml to configure the existing account: since the account is used by the entire Pod and not just the controller, it doesn't really make sense to configure it under the controller settings. Since it's effectively a Deployment-wide setting (Pod-wide, but we don't make the distinction), this would make more sense:

```
deployment:
  serviceAccount:
    create: false
    name:
    annotations: {}
```
We don't want to break existing configuration, however, so we'd keep the section under `ingressController` for now and still honor it if has non-default settings. The `kong.serviceAccountName` would return, in order of precedence:

1. `ingressController.serviceAccount.name`
2. `deployment.serviceAccount.name`
3. `(include "kong.fullname" .)` if `create=true` or `default` if `create=false`

Effectively, use the `name` from the `ingressController` section if it's set, since only users who'd intentionally changed the default in the past would have a value there. Annotations would be handled similarly, where we'd use the `ingressController` section value if set to anything other than the default empty object.

That allows us to smoothly transition to the new setting location without breaking existing configurations. We'd eventually deprecate and then remove the old location.

**Comment by ludovic-pourrat** [comment]
@rainest got it now! I was missing your point mainly because we deploy the ingress controller alone in one instance of the chart, separately from both the control plane and the data plane.
We might revert back then this approach and couple the ingress controller to the control plane helm chart instance.

The reason behind this request was because of our integration to the Vault injector agent, requiring us to have `serviceAccount` in place for granting access to the related Vault secrets.

Your proposal for setting up the serviceAccount name is ok for me. I will investigate a solution following that path and will advise accordingly.

Thanks.

**Comment by ludovic-pourrat** [comment]
@rainest, according to your feedback and proposal, this should look like this

For the values.yaml

```yaml
deployment:
  serviceAccount:
    create: false
    name: 
    annotations: {}
```

For the helper

``` yaml
{{- define "kong.serviceAccountName" -}}
{{- if .Values.ingressController.serviceAccount.name -}}
{{- if .Values.ingressController.serviceAccount.create -}}
    {{ default (include "kong.fullname" .) .Values.ingressController.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.ingressController.serviceAccount.name }}
{{- end -}}
{{- else -}}
{{- if .Values.deployment.serviceAccount.create -}}
    {{ default (include "kong.fullname" .) .Values.deployment.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.deployment.serviceAccount.name }}
{{- end -}}
{{- end -}}
{{- end -}}
```

and an additional service-account.yaml template as follow

```yaml
{{- if and .Values.deployment.kong.enabled .Values.deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kong.serviceAccountName" . }}
  namespace: {{ template "kong.namespace" . }}
  {{- if .Values.deployment.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.deployment.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
{{- end -}}
```

I have successfully tested this approach.

I will go further on testing (with focus on `podSecurityPolicy` enabled flag that could generate collisions) it and will raise a PR soon.

Thanks

**Comment by rainest** [comment]
@ludovic-pourrat checking in on this, would you be able to make a draft available? There was interest in this internally as well, since we need the token mounted for another of our products (Kuma) even when the controller isn't enabled, so if it's more or less ready we'd be interested in helping test it/work out any issues before merging it in.

**Comment by ludovic-pourrat** [comment]
@rainest yes I will proceed in the next 48h.

**Comment by xavipanda** [comment]
we also notice this behaviour... where we have to forcefully create the SA before the migrations.. otherwise they wont start.. impacting how kong can actually automatically deployed and managed by ArgoCD

**Comment by ludovic-pourrat** [comment]
@rainest I need to include the automountServiceAccountToken templating to make it work too, according comments from @ichasco-heytrade

Fixed by adding a test to enable the auto mounting the server account when required.

Deployment

``` yaml
{{- if or .Values.ingressController.enabled .Values.podSecurityPolicy.enabled .Values.deployment.serviceAccount.create }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: false
{{- end }}
``` 

Migrations

``` yaml
{{- if or .Values.podSecurityPolicy.enabled .Values.deployment.serviceAccount.create }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: false
{{- end }}
```

I will update and re-issue the PR accodingly.

**Comment by rainest** [comment]
So after playing around with options for the templates, I've concluded that there really isn't anything that'd support either configuration without making the template logic convoluted and verbose, so we may as well make an immediate breaking change with a warning if you've set either of the overrides in the ingressController config.

@ludovic-pourrat would you be able to reopen the PR and cherry-pick https://github.com/Kong/charts/pull/455/commits/24d185c2b8287f75ab2c19663af29fa02e15523f into it? I can open my own with content from your branch, but wanted to make sure you got credit for the PR.

**Comment by rainest** [comment]
Handled by #455

**Comment by ludovic-pourrat** [comment]
Nice work thanks a lot !
