### ISSUE TITLE
Migration jobs are not deleted after it runs to completion

### ISSUE THREAD

**Issue by weewey** [Kong/charts#44]
Despite the migration jobs having the following annotations
```
  annotations:
    helm.sh/hook: "post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
```
None of the migration jobs were deleted after the jobs runs successfully.

**Comment by hbagdi** [comment]
This is along the same lines of https://github.com/Kong/charts/pull/36

**Comment by hbagdi** [comment]
Wait, that looks like correct behavior.
The migration job will be deleted when the next time your run upgrade. Why do you want them to be deleted on successful run?

**Comment by rainest** [comment]
Our deletion policy choice is somewhat arbitrary: currently we leave the completed job around and only delete it when preparing to create a new one. This leaves the old job around in case you want to inspect it while still not blocking during upgrades: the old job will be removed right before Helm attempts to create the new one.

In practice, this probably isn't of much use, since the migrations output is usually only of interest when it fails, in which case using `hook-succeeded` wouldn't remove the job either. There are some edge cases where migrations will run successfully while still not doing what they should, but I wouldn't expect most users to encounter them.

**Comment by rainest** [comment]
@weewey do you know of any issues with the current approach (create, leave in place, remove immediately before creating a new version)? Functionally I'm not aware of any problems. I think the ideal solution is https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs to keep the jobs around for a short period and then delete them, but we can't use that until it's out of alpha and supported by managed K8S providers.

**Comment by weewey** [comment]
@rainest , @hbagdi 
Actually I'm fine with it `create, leave in place and remove before creating a new version`, however it does perform the delete. Hence I will have to manually delete the jobs before I run the upgrade command. 🤔

**Comment by rainest** [comment]
There's a bit of oddness here where the jobs that have the hook annotations mentioned in the original comment do get deleted, but the `init-migrations` job does not, because it has no annotations. Those are absent because Helm lacks some functionality we'd need to handle it effectively: https://github.com/Kong/charts/blob/master/charts/kong/FAQs.md#running-helm-upgrade-fails-because-of-old-init-migrations-job

The issue with `init-migrations` is tracked in #43, though it may be some time before we have more updates there; they'll depend on whether the Helm developers are open to adding the functionality we need.
