### ISSUE TITLE
HostPort with DaemonSet and nodeSelector options for a non LB deployment

### ISSUE THREAD

**Issue by giovannicandido** [Kong/charts#482]
Hi,
I'm would like to deploy kong in a infrastructure that doesn't allow or provide a LoadBalancer type of service. The way to do it is to create a external LoadBalancer Layer 7 in front of it with Cloudflare (or expose the node directly to internet by dns)
For this to work I need kong to be able to listen in the ports 80 (http) and 443 (https) of the nodes I select.
The way to do it is to provide a DaemonSet, hostNetwork and hostPort along with a nodeSelector to limit the nodes it deploys.

Is it possible to do with the current chart?

Thanks.

**Comment by rainest** [comment]
Everything other than the Pod hostNetwork setting is currently supported (`.proxy.http(s).hostPort=<port>` and so on for the various service configurations, `deployment.daemonset=true`, and `.nodeSelector`). Would you be willing to submit a PR to add `hostNetwork` via `deployment.kong.hostNetwork`?

You may not strictly need hostNetwork. It looks like https://developers.cloudflare.com/spectrum/how-to/create-load-balancer will allow you to map between external and internal ports to allow pointing to a non-standard port, which should allow you to use NodePorts instead. That may change other factors, however, since Cloudflare pricing and connection handling for Spectrum isn't the same as HTTP.

**Comment by giovannicandido** [comment]
Hi, I'm evaluating kong with NodePort. I works great so far (I didn't have the same luck with other ingress, I'm not sure if is a problem with my K8S setup).
If it stays stable and compatible with some features, like custom resource definitions. I will subimit a PR for hostNetwork option.
Thanks for the suggestion of using spectrum with nodeport, is good to have options.
