### ISSUE TITLE
Reloading custom plugins

### ISSUE THREAD

**Issue by dcarley** [Kong/charts#490]
Custom plugins that are provided with the values `plugins.configMaps` or `plugins.secrets` aren't currently reloaded when the underlying resources are updated. This has caused us some confusion on a number of occasions.

We can't use the [standard Helm trick of adding a checksum annotation](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) because the plugin files don't belong to the Kong chart. All of the solutions that we've found available to us so far are all pretty fragile:

- pre-process the values file to set `podAnnotations.checksum/plugins`
- post-process the chart to set an annotation
- update the name of the ConfigMap each time we change the plugins

An alternative solution could be for Kong to recognise and reload plugins when the [mounted ConfigMap changes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically) - although that may also be confusing if it's decoupled from normal Helm deployments.

Do you have any other suggestions?

**Comment by rainest** [comment]
This is an inherent limitation of how Kong handles plugins currently: it loads plugin files at startup, and never looks at them again unless you run `kong reload` (there's no good way to do so on Kubernetes--you'd need to shell into the individual containers and run it).

Handling this automatically on the fly when ConfigMaps update files on the filesystem would require a feature request to https://github.com/Kong/kong to automatically reload on changes to plugin files.

My recommendation here is to either run `rollout restart` manually or to build a custom container, i.e. create a Dockerfile based on the `kong/kong` image and either use `luarocks install` or copy files directly into `/usr/local/share/lua/5.1/kong/plugins`, build that, and push an upgrade that uses the new image, ideally from a CD system.

Nothing in the chart will ever be able to trigger an update within running containers, since at best we'd be able to perform a lookup on the ConfigMap to get its version and set an annotation to that value, which will just trigger a Deployment rollout anyway, and not provide any obvious advantage over just running `rollout restart`.
