### ISSUE TITLE
Chart is limited to a single hostname

### ISSUE THREAD

**Issue by ruiengana** [Kong/charts#496]
Latest Kong Chart limits Ingress to a single Hostname, this blocks ability to leverage Kong Routes with specific Hostnames.

Previous chart didn't had this limitation. Is this behaviour intended?

**Comment by rainest** [comment]
Yes, this was an intentional change for 2.0: https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md#removal-of-multi-host-proxy-ingress

That change allows us to use a single template for all Ingresses and Services, resolving a history of issues where we'd update one and forget to add feature parity in the other. The proxy shouldn't need multiple hostnames or, arguably, need its own Ingress at all in most cases. The ability to set multiple hostnames was a legacy configuration artifact that predated had existed since early versions of the chart, but was out of line with normal usage of Ingress resources.

You should instead be creating multiple Ingresses, one or more for each individual Service you wish to proxy. Those Ingresses can set hostnames for their rules, and our ingress controller will generate routes for each of those hostnames.

The old multi-hostname configuration predated our ingress controller, and was (AFAIK) primarily used in environments where another ingress controller sent traffic to Kong, which then had manually configured routes for all the hostnames on the proxy Ingress. Though we now recommend using our controller and exposing the proxy as a LoadBalancer, you can still use this topography by creating your own (not chart-managed) Ingress resources that point to the proxy. You should also be able to edit the proxy Ingress to add additional hostnames: Helm 3's diff logic should preserve them.
