### ISSUE TITLE
Kong chart 2.6.1: Bug in ingress class template

### ISSUE THREAD

**Issue by jeroen-s** [Kong/charts#497]
https://github.com/Kong/charts/blob/kong-2.6.1/charts/kong/templates/ingress-class.yaml

On line 3: `"kong"` should be `.Values.ingressController.ingressClass`

**Comment by rainest** [comment]
This uses a static value by design: it's only creating the default IngressClass that we use since we can reasonably assume that users may not have created it otherwise. If you use a non-default IngressClass, the expectation is that you manage it outside the chart because there's something you want to set that the template doesn't provide.

That resource is basically just a stub at this point: we create it to conform to Ingress v1, but as of yet the controller doesn't make any use of it (instead, the controller just confirms that the `ingressClassName` field on an Ingress matches the `--ingress-class VALUE` argument).

Does the current behavior cause any issues in your case? Absent any I'd expect to leave this as-is--maybe at most create an additional condition that disables creating the IngressClass if you do not use the default.
