### ISSUE TITLE
IngressClass being deleted and recreated

### ISSUE THREAD

**Issue by dcarley** [Kong/charts#512]
The `existingKongIngressClass` conditional around the `IngressClass` resource causes it to be deleted every other release. This means that you're non-deterministically unable to deploy `Ingress` resources with `spec.ingressClassName: kong`.

I couldn't tell from a4958208df084ac5de81a5a665e5e1e31ec033e9 why this condition is there. Is it intended to guard for people that have manually created the resource prior to the chart including it? If so, could the conditional be removed and the upgrade notes instruct people to [label the resource for adoption](https://github.com/helm/helm/pull/7649)? `helm.sh/resource-policy="keep"` doesn't seem like the right solution because it wouldn't allow for a clean uninstall.

I'd be happy to raise a PR if you can advise on the desired implementation and any additional tests.

---

First release on a fresh cluster creates it:
```
$ minikube start
😄  minikube v1.22.0 on Darwin 11.6
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.21.2 on Docker 20.10.6 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
$ helm upgrade kong kong/kong --install --version 2.6.2 --set ingressController.installCRDs=false | head -n1
Release "kong" does not exist. Installing it now.
$ kubectl get IngressClass/kong
NAME   CONTROLLER                      PARAMETERS   AGE
kong   konghq.com/ingress-controller   <none>       10s
```

Second release deletes it:
```
$ helm upgrade kong kong/kong --install --version 2.6.2 --set ingressController.installCRDs=false | head -n1
Release "kong" has been upgraded. Happy Helming!
$ kubectl get IngressClass/kong
Error from server (NotFound): ingressclasses.networking.k8s.io "kong" not found
```

Third release recreates it:
```
$ helm upgrade kong kong/kong --install --version 2.6.2 --set ingressController.installCRDs=false | head -n1
Release "kong" has been upgraded. Happy Helming!
$ kubectl get IngressClass/kong
NAME   CONTROLLER                      PARAMETERS   AGE
kong   konghq.com/ingress-controller   <none>       2s
```

**Comment by rainest** [comment]
Part to allow you to create your own but more because we do want that specific name and you can't install multiple releases into the same cluster if you remove it:

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "kong" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "bar": current value is "foo"
```

Since they are actually owned by another release, that'd preclude the adoption option.

We do [get the full object back from `lookup`](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function), so you should be able to modify the logic to create the resource if either of two conditions is true:
- The resource doesn't exist (the current condition)
- The resource exists, and the value of the `meta.helm.sh/release-name` annotation is equal to the `Release.Name` variable.

That way, whichever release created it originally will continue to include it on upgrades, but other releases will disable creating their own.

**Comment by dcarley** [comment]
Good call, thanks! I've raised https://github.com/Kong/charts/pull/518
