### ISSUE TITLE
failed to install CRD crds/custom-resource-definitions.yaml

### ISSUE THREAD

**Issue by ngingihy** [Kong/charts#544]
Hi, i'm provisioning a namespace not a whole cluster for installing Kong using helm. My administrator is not willing to grant me access, is there any workaround for this problem? Below is the error i'm getting 

> Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:test-kong-helm:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

**Comment by SimonSchmid** [comment]
I am having a similar issue. Our admins created the CRDs for us and I have the --skip-crds flag set during helm install. Though, the custom-resource-definitions.yaml file in the templates directory causes issues as it does a "lookup" for the kongplugins.configuration.konghq.com CRD. We don't have the permission for a CRD lookup though. I don't see a way to prevent that lookup through a configuration in the values file. The only solution I see is deleting that file (as it anyway does not seem to be required with Helm 3).

Do I oversee something? Or is the deletion of the file indeed the only way to solve the issue? If so, would be nice, if there could be a configuration option added to disable that file (or lookup) being used at all.

**Comment by ngingihy** [comment]
@SimonSchmid i deleted custom-resource-definitions.yaml file and  still installed kong with --skip-crds flag and the ingress.controller flag set to false and it worked!

**Comment by ngingihy** [comment]
@SimonSchmid  check https://github.com/Kong/charts/issues/427#issuecomment-1042008097

**Comment by SimonSchmid** [comment]
Yes, I get it to work like that as well but would prefer to not have to adapt the Kong Helm Chart, meaning have to delete the custom-resource-definitions.yaml file. I would have to do this each time I update e.g. the version.

**Comment by rainest** [comment]
Could either of you share input from your security teams as to why they have disabled and will not grant CRD Get permissions?

If there's a known reason that's considered a risk, we can look at reviewing options for removing the lookups. If it's simply a principle of least privilege concern where they did not expect chart installers would need this permission and therefore did not grant it, our using it should be grounds to grant it.

**Comment by rainest** [comment]
Reviewing the template, we do still honor the original `ingressController.installCRDs` setting, it's just not listed in values.yaml because you're not supposed to set it anymore normally.

If you explicitly set that to `false`, it will short-circuit the automatic legacy behavior detection, and installing the chart won't require the lookup. Do you see any issues still with that set?

**Comment by SimonSchmid** [comment]
Hi @rainest ,
thank you for the reply.

> Could either of you share input from your security teams as to why they have disabled and will not grant CRD Get permissions?

I think the issue is that accessing CRDs requires cluster-wide (not namespace bounded) access rights, no matter if Get or Write.

> If you explicitly set that to false, it will short-circuit the automatic legacy behavior detection, and installing the chart won't require the lookup. Do you see any issues still with that set?

Only if I set it to `false`, I come to the line where the lookup is made (line 23). If set `true`, in line 39 the CRD files are copied in an installed. That will cause a failure as well as CRD installation is also not permitted.
