### ISSUE TITLE
failed to manage services or routers when using nodePort on kubernetes

### ISSUE THREAD

**Issue by flower01840** [Kong/charts#571]
Hi all,
Kong Gateway admin port and manager port are both exposed by NodePort.
Browser requests container port when gets service list. How do I overwirte the port.
Thanks in advance. 
![image](https://user-images.githubusercontent.com/37743391/161380143-236ee6a9-630a-43f2-bbc6-1f6408cce19b.png)

**Comment by rainest** [comment]
You need to add `admin_gui_url` and `admin_api_uri` under `env` with values appropriate to however you're accessing those from outside the cluster. These are set for you when using the built-in Ingresses (https://github.com/Kong/charts/blob/3662583cf1e4c262794864aaa10aad4fcb4a8028/charts/kong/templates/_helpers.tpl#L711 and https://github.com/Kong/charts/blob/3662583cf1e4c262794864aaa10aad4fcb4a8028/charts/kong/templates/_helpers.tpl#L676), but not with NodePorts.

If not set at all, Kong will try and guess the values by overlaying the container port on top of the current URL, which is what you're seeing currently.

Will go ahead and close this since setting those should clear this issue, but if you have any additional questions please respond back and we'll reopen it.
