### ISSUE TITLE
Inconsistency with user defined volumes 

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/charts#585]
Since the changes applied to the ingress controller, the `userDefinedVolumeMounts` must be set to the `ingressController` item but the `userDefinedVolumes` definition remains under the deployment, which not that easy to setup.

This is not clear in the documentation.

What would you recommend as a change ?

**Comment by rainest** [comment]
Where were you looking in documentation? This is just how Kubernetes volumes work: volumes are declared at the Pod level (deployment in the chart since we place pod template config under there) whereas mounts are in the individual containers:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podspec-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#container-v1-core

https://github.com/Kong/charts/blob/b3e6644a27824d5b177caf515aabc7f2e96c7777/charts/kong/values.yaml#L506-L507 does mention that the volumes are in another section.

**Comment by ludovic-pourrat** [comment]
@rainest thanks for the calorification I missed it !

This issue can be marked as resolved then.
