### ISSUE TITLE
IngressClass is not deployed with ArgoCD

### ISSUE THREAD

**Issue by spoukke** [Kong/charts#587]
When I deploy kong with ArgoCD using the chart, the IngressClass is not deployed by default.

I think this is because of [this line](https://github.com/Kong/charts/blob/main/charts/kong/templates/ingress-class.yaml#L7). Indeed, since ArgoCD does not do any helm release, this annotation is never added.

It would be nice to change this condition with another annotation, which will exist whether or not the chart is installed through a Helm release.

For information, I use the 2.7.0 version.

**Comment by rainest** [comment]
Does ArgoCD provide any means to add arguments to the Helm executable? I suspect what you actually need is this:

```
--api-versions "networking.k8s.io/v1/Ingress" `--api-versions "networking.k8s.io/v1/IngressClass"
```

The IngressClass template has two types of conditionals, one set to [determine whether the cluster supports IngressClass at all](https://github.com/Kong/charts/blob/b3e6644a27824d5b177caf515aabc7f2e96c7777/charts/kong/templates/ingress-class.yaml#L3-L4) and another to [check if there's already an IngressClass in place](https://github.com/Kong/charts/blob/b3e6644a27824d5b177caf515aabc7f2e96c7777/charts/kong/templates/ingress-class.yaml#L5-L7).

If the resource isn't present _at all_ it should fall into the [final else condition](https://github.com/Kong/charts/blob/b3e6644a27824d5b177caf515aabc7f2e96c7777/charts/kong/templates/ingress-class.yaml#L14), which does create it. That should work on the initial install--the resource lookup/name comparison should only matter for upgrades of existing installs. However, `helm template` has a wide variety of limitations, one of which being that it doesn't consult the cluster to determine the API versions available, which will make our chart fall back to using an older version of Ingress prior to the introduction of IngressClass.

https://github.com/argoproj/argo-cd/issues/3631 indicates that Argo should set those automatically, but that there's apparently some issue with Helm 2 charts. Upgrading to 2.8 may fix this, since we just recently converted to the Helm 3 chart format.

I'm not quite sure what would happen after on upgrades--it depends on how ArgoCD is handling the release management/resource deletion/etc. that'd normally be handled by Helm when using `install` instead of `template`. If `template` can't perform the lookup (which I think is the case), it should just treat this as a fresh install with no existing IngressClass and continue to render it.
