### ISSUE TITLE
New installs of v2.8.2 missing RBAC permissions for IngressClass

### ISSUE THREAD

**Issue by readverish** [Kong/charts#607]
When installing v2.8.2 with `ingressController.watchNamespaces` set to ["default"], the `ingress-controller` logs the following error and remains in cyclic restarts:

E0606 17:16:56.258537       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1.IngressClass: failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:default:kong-kong" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

It seems that the ingress-controller requires access to the IngressClass API resources, which are cluster level resources, even if a specific namespace to watch is specified.

See issue [#2541 in kubernetes-ingress-controller.](https://github.com/Kong/kubernetes-ingress-controller/issues/2541)

The following patch to `kong/templates/controller-rbac-resources.yaml` fixes the problem:

```diff
89d88
< {{- if eq (len .Values.ingressController.watchNamespaces) 0 }}
97a97
> {{- if eq (len .Values.ingressController.watchNamespaces) 0 }}
98a99
> {{- end }}
115c116
< {{- else }}
---
> {{- if gt (len .Values.ingressController.watchNamespaces) 0 }}
```

**Comment by rainest** [comment]
My plan here is actually to restore a ClusterRole even with a namespace watch set.

When this feature was originally designed, the only cluster-scoped resource we used was our own KongClusterPlugin, which had a namespaced equivalent, albeit with some reduction in functionality, so using only namespaced permissions was viable.

Since, Ingress has added IngressClass and Gateway APIs has added GatewayClass. These are cluster-scoped resources designed by the CNCF, and there is no namespaced equivalent of them. I take that as a strong indication that any proper implementation of those API suites requires those cluster-level permissions, and that cluster admins who have issues granting those permissions need to take up their concerns with the CNCF. I think it should be entirely reasonable to grant them: those resources do not contain obviously sensitive data and the namespace-scoped mode will still restrict access to resources that are sensitive, e.g. Secrets.

**Comment by readverish** [comment]
> My plan here is actually to restore a ClusterRole even with a namespace watch set.
> 
This is pretty much what I propose in the suggested change, always create the ClusterRole and ClusterRoleBinding, regardless of the watchedNamespaces setting, the only difference is the content of the ClusterRole. Thank you.

**Comment by jasiek-zywczak** [comment]
the behaviour of charts is (almost) correct, when we are running kong in the cluster we should not require cluster role, the problem is that chart is not disable watching the ingressClass in that case 
https://github.com/Kong/charts/issues/648
