### ISSUE TITLE
Use the priority order of using fullNameoverride > dependency chart nameOverride > releaseName for Postgres

### ISSUE THREAD

**Issue by scseanchow** [Kong/charts#650]
The postgres name always uses the kong chart release name (https://github.com/Kong/charts/blob/3662583cf1e4c262794864aaa10aad4fcb4a8028/charts/kong/templates/_helpers.tpl#L43). Use the priority order of using fullNameoverride > dependency chart nameOverride > releaseName

**Comment by mflendrich** [comment]
Per @rainest, it might be technically difficult to propagate the name to the Postgres subchart.

Requires feasibility investigation.

**Comment by rainest** [comment]
They likely will need to use https://github.com/bitnami/charts/blob/c8240ddf458fb9fc48b84c5334c8132bf05aa91a/bitnami/postgresql/values.yaml#L51-L56 instead, i.e. set the same overrides through both the Kong and Postgres values.

**Comment by rainest** [comment]
Alright, further investigation/confirmation:
- https://helm.sh/docs/chart_template_guide/subcharts_and_globals/ does not provide a general-purpose mechanism to set a subchart value to the output of a template in the parent (although I kinda wish Helm had this feature).
- AFAIK you can only do this if the subchart author chose to process that value in their chart using the `tpl` function, i.e. rather than the normal basic YAML type behavior the field evaluates a template and then does something with it, in which case we'd be able to pre-populate `postgresql.fullnameOverride: {{ include "kong.name" }}` or whatever. The Bitnami Postgres chart does not do this.
- The Bitnami Postgres chart does provide their own `fullnameOverride` already, so you'll instead just need to set it twice, e.g. `fullnameOverride: MyCoolName` and `postgresql.fullnameOverride: MyCoolName`.

Closing as not possible but with a reasonable alternative.
