### ISSUE TITLE
Support autoscaling/v2

### ISSUE THREAD

**Issue by randmonkey** [Kong/charts#667]
Now the chart support `autoscaling/v1` and `autoscaling/v2beta2` for auto scaling.  `autoscaling/v2beta2` is deprecated in k8s 1.23 and will be removed in k8s 1.26 (expected to be released this year). So we are considering to support `autoscaling/v2` API.
## Acceptance Criteria
- [ ] In k8s >= 1.23 (including the upcoming 1.26),resources in `autoscaling` has cersion `autosacling/v2`
- [ ] In k8s <= 1.22, `autoscaling/v2beta2` is  still supported.

**Comment by rainest** [comment]
We'll also need to review how far back v2 is supported. If it'd break compatibility with all but the most recent versions, we'll want to add a lookup switch that creates whichever version is available.

Currently KIC support goes back through 1.22, so we'll want to support at least that far back.

**Comment by pmalek** [comment]
Just wanted to note that to make this work we don't strictly need to drop support for older versions just yet because we can use some of the helm's logic to make it deduce cluster capabilities and use appropriate HPA version this way, just like it's already done e.g. here https://github.com/Kong/charts/blob/632a6f7202fc51ddf2f2b78c88e10b8c456eb543/charts/kong/templates/hpa.yaml#L2
