### ISSUE TITLE
Kong manager is not installed on non enterprise version

### ISSUE THREAD

**Issue by istvancaluser** [Kong/charts#670]
Current chart does setup kong manager although official documentation allows usage of kong manager in free version.
https://docs.konghq.com/gateway/latest/#kong-manager
Issue is at 

https://github.com/Kong/charts/blob/969273853af9ccc7a407c7badbff27f3dc0ff91e/charts/kong/templates/service-kong-manager.yaml#L2

It expects kong enterprise to be enabled.

**Comment by rainest** [comment]
This is just a naming convention. You should enable it if you wish to use the additional features available in the kong-gateway image.

The `enterprise` section predates the availability of free mode. We did not rename it when that became available because doing so would break existing configurations--in general, because the names of settings in values.yaml are significant, we only change them if there's a pressing need. Despite the name, the `enterprise` section still serves the same purpose, controlling features that are available in the kong-gateway image but not in the kong image.

You can still enable Manager there without setting a license.

I'll go ahead and close this but let us know if you have any further questions.
