### ISSUE TITLE
pre-upgrade-migrations hitting k8s label name limit

### ISSUE THREAD

**Issue by CharlesTME** [Kong/charts#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1.4

### Current Behavior

After deployed helm release for admin :
`helm upgrade -i kong-ee-aws-admin-2-8-1-4-hybrid-prev kong/kong -n namespace -f values.yaml`

Upgrading deployment of admin release with helm upgrade trigger a migration job 'kong-pre-upgrade-migrations'

from Github chart, migrations-pre-upgrade.yaml values files : (https://github.com/helm/charts/blob/master/stable/kong/templates/migrations-pre-upgrade.yaml), name of the job are set with :
`name: {{ template "kong.fullname" . }}-pre-upgrade-migrations`

`-kong-pre-upgrade-migrations` is 28 characters
To not exceed k8s label name limit of 63 chars, helm release name should not exceed 35 characters (63 - 28 = 35). 

In my case, my helm release name is > 35 characters, helm upgrade hence following error :

`failed: Job.batch "kong-ee-aws-admin-2-8-1-4-hybrid-prev-kong-pre-upgrade-migrations" is invalid: spec.template.labels: Invalid value: "kong-ee-aws-admin-2-8-1-4-hybrid-prev-kong-pre-upgrade-migrations": must be no more than 63 characters`

Upgrade fail, and it is not possible to use helm upgrade.

### Expected Behavior

When deploying helm release for admin with name > 35 characters could trigger warning or error about helm release naming size

### Steps To Reproduce

```markdown
1 Deploy Kong with release name with at least 36 characters
2 Helm upgrade to hence jobs pre-upgrade-migrations
```

**Comment by hbagdi** [comment]
cc @rainest

**Comment by rainest** [comment]
I'm not sure there's a good way to alert on these. AFAIK Helm doesn't really have any notion of pre-flight checks that you can validation prior to rendering templates. NOTES.txt is the closest equivalent, but it's just a special-purpose template, and renders at the same time as other templates.

https://helm.sh/docs/topics/charts/#schema-files should let us define a max length for fields, but the release name isn't actually a values field. I think anything that validates it would have to be built into Helm itself.

Do you know of a Helm feature that would work well here? Otherwise I'd recommend shortening the release name or setting a `nameOverride` or `fullnameOverride` value (these [replace part and all of the release-derived name](https://github.com/Kong/charts/blob/main/charts/kong/templates/_helpers.tpl#L19-L22) used throughout other templates). We can add an entry to the common problems document, but probably can't interrupt the Helm commands.

**Comment by pmalek** [comment]
What's interesting though is that it doesn't complain about the name (which indeed is more than 63 characters) but about the labels value which as far as I can see is not set to the `$RELEASE-pre-upgrade-migrations` 🤔 

I've just tested this and installing the chart with the same flags as you've specified and default [`values.yaml`](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml) didn't yield an error.

```
helm upgrade -i kong-ee-aws-admin-2-8-1-4-hybrid-prev kong/kong -n kong-chart -f charts/kong/values.yaml
Release "kong-ee-aws-admin-2-8-1-4-hybrid-prev" does not exist. Installing it now.
NAME: kong-ee-aws-admin-2-8-1-4-hybrid-prev
LAST DEPLOYED: Tue Oct 11 10:15:20 2022
NAMESPACE: kong-chart
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To connect to Kong, please execute the following commands:

HOST=$(kubectl get svc --namespace kong-chart kong-ee-aws-admin-2-8-1-4-hybrid-prev-kong-proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
PORT=$(kubectl get svc --namespace kong-chart kong-ee-aws-admin-2-8-1-4-hybrid-prev-kong-proxy -o jsonpath='{.spec.ports[0].port}')
export PROXY_IP=${HOST}:${PORT}
curl $PROXY_IP

Once installed, please follow along the getting started guide to start using
Kong: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/getting-started/
```


```
helm ls -A
NAME                                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kong-ee-aws-admin-2-8-1-4-hybrid-prev   kong-chart      2               2022-10-11 10:17:45.069619 +0200 CEST   deployed        kong-2.13.1     3.0
```

Have you tried running `helm repo update` to ensure you have the latest version available for installation?
