### ISSUE TITLE
Retry not triggered on a read_timeout

### ISSUE THREAD

**Issue by SimonSchmid** [Kong/charts#708]
Hi all,

I have an issue where I am not sure if I am doing/understanding sth. wrong or if it is a bug.
I have a Service deployed where I have the following annotations set
```
konghq.com/read-timeout: 1000
konghq.com/retries: 3 
```

A request to the service takes two seconds to respond which means that it runs into a read timeout. What I would expect is that the request will be retried three times but instead it is not retried at all.

So my first question: Is my expectation correct? Or do retries not happen on read timeouts? I found that post that supports my expectation: https://discuss.konghq.com/t/set-timeout-for-the-whole-request-process-including-retries/6377/4

My second question would be: What could it be that I have configured incorrectly? The read-timeout is correctly applied, so I know that the kong configurations I set via the annotations in general seem to be applied.

I am using version 2.14 of the chart.

Best,
Simon

**Comment by rainest** [comment]
Are you seeing incorrect configuration, where the generated Service does _not_ have `read_timeout: 1000` set when you check the admin API? If so, that should be submitted to https://github.com/Kong/kubernetes-ingress-controller/issues

If you're seeing correct configuration, but unexpected behavior, that should be submitted to https://github.com/Kong/kong/discussions or https://github.com/Kong/kong/issues (the latter if you have data that appears to clearly indicate a bug).

You should review the `non_idempotent` section of http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream. IIRC there are some requests that NGINX will _never_ retry on failure without that set. If you're only seeing this behavior on `POST` requests (or other non-idempotent requests), that's likely part of the issue. By default NGINX won't retry those because it does not know if the request succeeded (it may have gone through even if no response came back to confirm), and re-sending non-idempotent requests can cause unexpected effects. I'm not quite sure where you'd need to tune that to override it (our NGINX config template doesn't have a `proxy_next_upstream`), so if it looks like that, the Kong/kong discussions board is probably your best bet to discuss it with someone more familiar with the proxy internals.

Closing this as it's not something related to the chart.
