### ISSUE TITLE
Environment variable type safety without interface breakage

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#730]
#728 implemented strong type checks on the env variables for KIC and Gateway containers that are breaking (require you to explicitly specify the type in the helm CLI, among others).

The scope of this issue is to make this behavior less disruptive before releasing. We made an overly breaking decision in #701 and are now trying to make it less breaking.

## Acceptance criteria
- [x] `--set` works without the need for `--set-string` for ints, bools and strings
- [x] existing values.yaml configs that use bools and ints continue to work fine
- [ ] ints and booleans are implicitly converted (weak typing) to strings acceptable as env var values

**Comment by randmonkey** [comment]
partial fixed by #733 to just disable envvars for `*_log` to use booleans.

**Comment by mflendrich** [comment]
@rainest please verify if done already and close if so

**Comment by rainest** [comment]
AFAIK https://github.com/Kong/charts/pull/733 does indeed complete this. Satisfies the first two AC; explicitly does not satisfy the last because it avoids breakage by not performing general type coercion. It does perform type coercion for the known problem envvars where we definitely want to change to string. It intentionally does not coerce other envvars because allowing native YAML type interpretation does not break them--NGINX log envvars are unique in treating `true` and `false` as a filepath instead of a boolean disable because they accept a pseudo-boolean (`off` only as a falsy value) in a special case and a string otherwise..
