### ISSUE TITLE
Kong Manager objects not materializing despite being enabled in values.yaml

### ISSUE THREAD

**Issue by HariSekhon** [Kong/charts#782]
Hi,

It looks like Kong Manager is not being enabled when not in enterprise mode, even though iirc Kong Manager is available in the free version.

https://docs.konghq.com/gateway/3.2.x/#packages-and-modes

In the chart values yaml I have this:

```yaml
manager:
  enabled: true
```

which you can see in full here:

https://github.com/HariSekhon/Kubernetes-configs/blob/c858fd316b4a9abe5fc1c82cf9d7e34523262cc3/kong-values.yaml#L180

## Quickly Reproduce

You can quickly reproduce this using `helm template` with my public config template `kong-values.yaml` on GitHub:

```shell
git clone https://github.com/HariSekhon/Kubernetes-configs k8s
cd k8s
helm template kong/kong -f kong-values.yaml > /tmp/kong.yaml
grep -i manager /tmp/kong.yaml
```

Is it possible to get Kong Manager to deploy in open source Kong in this helm chart given the docs say it should be available in the open source version?

**Comment by mickey-bob** [comment]
i get same issue. Does anyone fix it ????

**Comment by rainest** [comment]
The chart values names are somewhat tied to product terminology from earlier releases. We can't easily change them in the chart because it'd break existing configurations.

Generally speaking, the chart uses `enterprise` to refer to any of the features (including Kong Manager) not available when using the entirely OSS distribution, https://hub.docker.com/_/kong

The https://hub.docker.com/r/kong/kong-gateway/ distribution includes additional functionality that is not OSS. Free non-OSS functionality is still managed under the `enterprise` section of the chart values.yaml, even though it does not require a license.

**Comment by HariSekhon** [comment]
@mickey-bob Looks like setting enterprise to true, manager enabled to true, and then the other components like portal enabled to false results in the extra yaml for the kong manager service and ingress being generated. I've updated my yaml on github to show this:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/kong/base/kong-values.yaml
