### ISSUE TITLE
Have helm upgrade error out if image tag values are not supplied

### ISSUE THREAD

**Issue by chadningle** [Kong/charts#805]
Currently, the helm chart will default to the latest version of Kong Gateway if an image tag is not supplied.  For helm install, this is fine.  For helm upgrade, request that the helm upgrade errors out if the image tag is not explicitly provided in the values file.

The reason for this request is that we had a customer trying to modify their existing Kong deployment via helm upgrade but we forgot to specify the tag.  It then defaulted to 3.2 when they were on 2.8.x.  This caused DB instability issues so we would like to have the upgrade action require more explicit values in the file when it comes to versions.

**Comment by pmalek** [comment]
Checking whether we're upgrading or installing should be doable via `Release.IsUpgrade` and `Release.IsInstall`: https://helm.sh/docs/chart_template_guide/builtin_objects/

Yet checking if the supplied value was provided would be tricky since we provide the default `image.tag` and I'm not aware of a way to differentiate between user supplied values and those defined in chart's `values.yaml`.

Each chart version has it's own `image.tag` and `appVersion` in https://github.com/Kong/charts/blob/main/charts/kong/Chart.yaml#L15 which should be equal. This way one can check what version would be deployed if nothing was specified by the user.

When deploying the chart, one could also use `helm template ...` using the same flags as provided to `helm upgrade ...` to get the rendered manifests.

Having said that I'm not sure if what's proposed here would be the desired (if possible) flow ( and whether that would align with what other charts are doing, I personally have not encountered such a requirement)

**Comment by rainest** [comment]
A warning in NOTES.txt would be preferable to an error. We do recommend pinning versions in general, but just leaving the defaults in place doesn't necessarily break anything--you can almost always do it for DB-less mode, and DB mode is fine (it will run migrations for you) unless you're skipping over versions that you must upgrade to before later ones.

However, lack of ability to distinguish between user-set values and values obtained from the default values.yaml makes detecting this impossible AFAIK, so I think it makes sense to close this as not implementable.
