### ISSUE TITLE
Why kong deployment does not have allowPrivilegeEscalation and runAsNonRoot?

### ISSUE THREAD

**Issue by smartaquarius10** [Kong/charts#820]
Hello,

This command is showing violation in kong deployment using its helm chart.

`kubectl label --dry-run=server --overwrite ns --all pod-security.kubernetes.io/enforce=restricted`

**Violation**
` allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, seccompProfile`

Is there any specific reason behind running it with root privileges. Kindly suggest. Thank you
```[tasklist]
### Tasks
```

**Comment by pmalek** [comment]
Hi @smartaquarius10 

You can specify kong container's `containerSecurityContext` via `.Values.containerSecurityContext`, e.g.

```
containerSecurityContext:
  allowPrivilegeEscalation: false
```

As far as I can see one cannot use `runAsNonRoot` set to `true` because:

```
  initContainerStatuses:
  - image: kong/kong-gateway-dev:latest
    imageID: ""
    lastState: {}
    name: clear-stale-pid
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'container has runAsNonRoot and image has non-numeric user (kong),
          cannot verify user is non-root (pod: "gw-kong-6dc7cfb678-fhdpw_kong(0f9562b0-be30-47ee-82f4-088a9761d829)",
          container: clear-stale-pid)'
        reason: CreateContainerConfigError
```

but that you might want to raise with https://github.com/Kong/kong.

I'm closing this since it's already possible to specify `containerSecurityContext` and that solves the described issue. Feel free to comment if you are still having problems with this.
