### ISSUE TITLE
Failed to pull image "kong:3.3" You have reached your pull rate limit.

### ISSUE THREAD

**Issue by byangtri** [Kong/charts#824]
`Failed to pull image "kong:3.3": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`
[Docker Hub limits the number of Docker image downloads, or pulls based on the account type of the user pulling the image](https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=Docker%20Hub%20limits%20the%20number,pulls%20per%206%20hour%20period.)
Kong still uses DockerHub to store container images. Is there a docker registry for Kong outside of Docker Hub’s rate limits, or any upcoming solution around this?

**Comment by pmalek** [comment]
Hi 👋 

At this moment, Gateway images are only provided through hub.docker.com.

We might look into mirroring the images to other site but there are no plans for that yet.

You're best bet for now would be to rely on your PaaS and to perform the mirroring yourself.

This might change but since - as mentioned above - there are no plans for that yet, I'm going to close this. Feel free to reach out to us if you have further questions on this.
