### ISSUE TITLE
Kong ingress-controller container missing lifecycle configurations

### ISSUE THREAD

**Issue by majid-akbari** [Kong/charts#868]
The Kong Helm Chart support adding lifecycle configurations only for `proxy` container and not `ingress-controller`.
Also there is an config directive for `ingress-controller` container as `--term-delay` but it don't have any affect on container when it is getting an SIGTERM signal.
Please add this lifecycle for `ingress-controller` container in your Helm Chart.

**Comment by rainest** [comment]
Do you know why the controller would need any? AFAIK we have these on the gateway because it may be actively handling requests when Kubernetes decides to terminate the Pod, and we want to give those time to complete without accepting new connections.

It should be fine to terminate the controller immediately for the most part. It doesn't really handle individual requests in the same way, since it just tries to sync Kong to the current state available from Kubernetes resources. Updates will be delayed while it's restarting, but you can't really avoid that--the restart has to happen eventually.

A shutdown request _during_ an update could potentially cause issues, but if you're seeing that we'd probably want to add better signal handling code in https://github.com/Kong/kubernetes-ingress-controller. A manifest-level delay wouldn't know the internal process state and whether it needs/how long it needs to delay.

**Comment by rainest** [comment]
Can you also confirm what you've tried to configure? https://github.com/Kong/kubernetes-ingress-controller/commit/fb7a4d0af3452babe7bc81346764f78e73506595 should honor that value.

That said I'm unsure that would work for its stated purpose. If we are draining connections from the proxy (as we should), we shouldn't be able to start new config update requests, only finish ongoing ones.

**Comment by majid-akbari** [comment]
Yes, I tried that option but then I found I don't need to keep ingress controller container alive. Only keeping proxy container works for my purpose.
