### ISSUE TITLE
add option for global https redirect in ingress controller chart

### ISSUE THREAD

**Issue by nwsparks** [Kong/charts#882]
This may be the wrong place for the issue, apologies if so.

I've researched pretty exhaustively looking for a way to globally redirect all http traffic to https without finding a solution.

The nginx ingress controller has such an option https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#auth-and-ssltls:~:text=False-,ssl%2Dredirect,-Sets%20an%20unconditional

and is configurable in their helm chart here https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx#:~:text=%5B%5D-,controller.config,-object

could something like this be included for the kong ingress controller?

**Comment by rainest** [comment]
Kong creates HTTPS redirects for routes that only allow the HTTP protocol. You can find an example of this at https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/configuring-https-redirect/

Kong does not have any configuration that does this for all routes by default. Were it to add it, I expect this would come as a feature allowing you to modify the [default route protocol](https://github.com/Kong/kong/blob/311f807b38659d6878b847a1f23a9ac1a3b0fd5c/kong/db/schema/entities/routes.lua#L57) to `https` instead of `http,https`.

While the controller could technically apply its own default, we normally try to follow Kong's default behavior unless there's a Kubernetes standard that indicates we should do otherwise, and try to add features to the proxy when they (like this one) make sense for both Kubernetes and non-Kubernetes environments. Please submit a feature request to the [proxy feature request board](https://github.com/Kong/kong/discussions/categories/ideas-and-feature-requests) for review by the proxy engineering team.
